A/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('o/', include('social_django.urls', namespace='social')),
]

accounts/urls.py
from django.urls import path, include
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView,	TokenRefreshView


app_name = 'accounts'

api_urls = [
	path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
	path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
	path('register/', views.UserRegister.as_view(), name='register'),
	path('login/', views.UserLogin.as_view(), name='login'),
	path('logout/', views.UserLogout.as_view(), name='logout'),
	path('dashboard/<str:username>/', views.UserDashboard.as_view(), name='dashboard'),
	path('api/', include(api_urls)),
]

core/urls.py
from django.urls import path, include
from . import views
from . import api_views


app_name = 'core'

api_urls = [
	path('questions/', api_views.QuestionListView.as_view()),
	path('questions/create/', api_views.QuestionCreateView.as_view()),
	path('questions/update/<int:pk>/', api_views.QuestionUpdateView.as_view()),
	path('questions/delete/<int:pk>/', api_views.QuestionDeleteView.as_view()),
	path('answers/create/', api_views.AnswerCreateView.as_view()),
	path('answers/update/<int:pk>/', api_views.AnswerUpdateView.as_view()),
	path('answers/delete/<int:pk>/', api_views.AnswerDeleteView.as_view()),
]

urlpatterns = [
	path('', views.Home.as_view(), name='home'),
	path('bucket/', views.BucketHome.as_view(), name='bucket_home'),
	path('bucket_delete/<str:key>/', views.BucketDelete.as_view(), name='bucket_delete'),
	path('bucket_download/<str:key>/', views.BucketDownload.as_view(), name='bucket_download'),
	path('api/', include(api_urls)),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='1.jpg')

	def __str__(self):
		return self.user.username

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Question(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.title[:20]}'

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super().save(*args, **kwargs)


class Answer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answers')
	question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.question.title[:20]}'

accounts/forms.py
from django import forms
from .models import Profile


class UserRegistrationForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class UserLoginFrom(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class ProfileImageForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('image',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import UserRegistrationForm, UserLoginFrom, ProfileImageForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile


class UserRegister(View):
	form_class = UserRegistrationForm
	template_name = 'accounts/register.html'

	def get(self, request):
		form = self.form_class
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = User.objects.create_user(cd['username'], cd['email'], cd['password'])
			Profile.objects.create(user=user)
			messages.success(request, 'you registered successfully', 'info')
			return redirect('core:home')
		return render(request, self.template_name, {'form':form})


class UserLogin(View):
	form_class = UserLoginFrom
	template_name = 'accounts/login.html'

	def get(self, request):
		form = self.form_class
		return render(request, self.template_name, {'form':form})

	def post(self, request):
		form = self.form_class(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(request, username=cd['username'], password=cd['password'])
			if user is not None:
				login(request, user)
				messages.success(request, 'you logged in successfully', 'info')
				return redirect('core:home')
			messages.error(request, 'username or password is wrong', 'warning')
		return render(request, self.template_name, {'form':form})


class UserLogout(LoginRequiredMixin, View):
	def get(self, request):
		logout(request)
		messages.success(request, 'you logged out successfully', 'info')
		return redirect('core:home')


class UserDashboard(LoginRequiredMixin, View):
	template_name = 'accounts/dashboard.html'
	form_class = ProfileImageForm

	def get(self, request, username):
		user = get_object_or_404(User, username=username)
		return render(request, self.template_name, {'user':user, 'form':self.form_class})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST, request.FILES, instance=request.user.profile)
		if form.is_valid():
			form.save()
			messages.success(request, 'your image updated successfully', 'info')
			return redirect('accounts:dashboard', request.user.username)

core/views.py
from django.shortcuts import render, redirect
from django.views import View
from . import tasks
from django.contrib import messages
from permissions import IsSuperUserMixin


class Home(View):
	def get(self, request):
		return render(request, 'core/home.html')


class BucketHome(IsSuperUserMixin, View):
	template_name = 'core/bucket.html'

	def get(self, request):
		objects = tasks.all_bucket_objects_task()
		return render(request, self.template_name, {'objects':objects})


class BucketDelete(IsSuperUserMixin, View):
	def get(self, request, key):
		tasks.delete_object_task.delay(key)
		messages.success(request, 'your request will done soon...', 'info')
		return redirect('core:bucket_home')


class BucketDownload(IsSuperUserMixin, View):
	def get(self, request, key):
		tasks.download_object_task.delay(key)
		messages.success(request, 'your download will start soon', 'info')
		return redirect('core:bucket_home')

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center">{{ user.username }}</h3>
    <img src="{{ user.profile.image.url }}" class="rounded mx-auto d-block">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="upload">
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" novalidate class="col-md-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

    <a href="{% url 'social:begin' 'github' %}" class="btn btn-info">Github</a>
    <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger">Google</a>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" class="col-md-5" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

core/templates/core/bucket.html
{% extends 'base.html' %}
{% load extra_filters %}

{% block content %}

<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Size</th>
        <th scope="col">Download</th>
        <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in objects %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ obj.Key }}</td>
            <td>{{ obj.Size|converter }}</td>
            <td><a href="{% url 'core:bucket_download' obj.Key %}">download</a></td>
            <td><a href="{% url 'core:bucket_delete' obj.Key %}">delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
    <h3>Home</h3>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class="alert alert-{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'core:home' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link active" href="{% url 'accounts:dashboard' request.user.username %}">dashboard</a>
        <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
        <a class="nav-link active" href="{% url 'accounts:register' %}">Register</a>
        <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
        {% if request.user.is_superuser %}
        <a class="nav-link active" href="{% url 'core:bucket_home' %}">Bucket</a>
        {% endif %}
    </div>
</nav>